export const POST_CONSENT = "POST_CONSENT";
export const POST_CONSENT_SUCCESS = "POST_CONSENT_SUCCESS";
export const POST_CONSENT_FAIL = "POST_CONSENT_FAIL";

export const GET_CONSENTS = "GET_CONSENTS";
export const GET_CONSENTS_SUCCESS = "GET_CONSENTS_SUCCESS";
export const GET_CONSENTS_FAIL = "GET_CONSENTS_FAIL";